#!/usr/bin/env python
import os
import sys

env = SConscript("../../../godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "build/bin/libcxxkodotlin.{}.{}.framework/libcxxkodotlin.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
        LIBS = ["rust"],
        LIBPATH = ["../rust/target/release"]
    )
elif env["platform"] == "ios":
    if env["ios_simulator"]:
        library = env.StaticLibrary(
            "build/bin/libcxxkodotlin.{}.{}.simulator.a".format(env["platform"], env["target"]),
            source=sources,
            LIBS = ["rust"],
            LIBPATH = ["../rust/target/release"]
        )
    else:
        library = env.StaticLibrary(
            "build/bin/libcxxkodotlin.{}.{}.a".format(env["platform"], env["target"]),
            source=sources,
            LIBS = ["rust"],
            LIBPATH = ["../rust/target/release"]
        )
else:
    library = env.SharedLibrary(
        "build/bin/libcxxkodotlin{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
        LIBS = ["rust"],
        LIBPATH = ["../rust/target/release"]
    )

Default(library)
